### ISSUE TITLE
Use a known license name

### ISSUE THREAD

**Issue by narkisr** [nwillc/fun-jdbc#2]
Hey @nwillc, it seems that you license is permissive enough for commercial use but its not a standard license, could you please set an existing license (Apache 2/MIT/BSD what ever you may choose)

Thanks!

**Comment by narkisr** [comment]
In bintray the license is set to Apache V2 so I guess this answers my question, still would be nice to explicitly state the name

Thanks

**Comment by narkisr** [comment]
https://en.wikipedia.org/wiki/ISC_license ?

https://bintray.com/nwillc/maven/fun-jdbc/view

**Comment by nwillc** [comment]
Yup ISC license.... in place and on bintray too
